language: node_js
node_js:
  - "10"
  - "12"
  - "14"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
before_install: "sudo apt-get update && sudo apt-get install -y libcairo2-dev libjpeg8-dev libgif-dev optipng pngcrush pngquant libpango1.0-dev graphicsmagick libjpeg-turbo-progs inkscape gifsicle"
script: "npm run-script travis"
after_success: '<coverage/lcov.info ./node_modules/coveralls/bin/coveralls.js'
